# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/DotCast.sln'
  displayName: 'Restore Nuget Packages'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/ProductivityStation.Web.csproj'
    arguments: '/p:DefineConstants=LINUX -r linux-x64 --configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/ProductivityStation.Web.csproj'
    arguments: '/p:DefineConstants=LINUX -r linux-x64 --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: false
    zipAfterPublish: false
  displayName: 'Publish'

- task: Docker@2
  inputs:
    containerRegistry: 'Private Registry'
    repository: DotCast
    tags: $(Build.BuildId)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: $(Build.ArtifactStagingDirectory)