# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: 'Replace submodule URLs with PAT and pull submodules'
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
      Write-Host "Adding PAT to submodule URLs"

      # Ensure the PAT environment variable is available
      if (-not $env:PAT) {
        Write-Error "PAT environment variable is not set."
        exit 1
      }

      # Get the submodule URLs from .gitmodules
      $submodules = git config -f .gitmodules --get-regexp '^submodule\..*\.url$' | Out-String

      # Split the output into lines
      $lines = $submodules -split "`n"

      foreach ($line in $lines) {
        # Skip empty lines
        if ([string]::IsNullOrWhiteSpace($line)) {
          continue
        }

        # Split the line into key and value
        $parts = $line -split '\s+', 2
        $key = $parts[0]
        $url = $parts[1]
        Write-Host "Processing $key"

        # Insert the PAT into the URL
        # Replace existing authentication info (if any) with the PAT
        $new_url = $url -replace 'https://[^@]*@', "https://$($env:PAT)@"

        # If there was no existing auth info, insert the PAT after https://
        if ($new_url -eq $url) {
          $new_url = $url -replace 'https://', "https://$($env:PAT)@"
        }

        # Update the .gitmodules file
        git config -f .gitmodules $key $new_url
      }

      # Synchronize the submodule URLs
      git submodule sync

      # Pull the submodule code
      git submodule update --init --recursive

      # Reset the .gitmodules file to avoid committing the PAT
      git checkout .gitmodules
  env:
    PAT: $(PAT)

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/DotCast.sln'
  displayName: 'Restore Nuget Packages'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/DotCast.App.csproj'
    arguments: '/p:DefineConstants=LINUX -r linux-x64 --configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/DotCast.App.csproj'
    arguments: '/p:DefineConstants=LINUX -r linux-x64 --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: false
    zipAfterPublish: false
  displayName: 'Publish'

- task: Docker@2
  inputs:
    containerRegistry: 'Private Registry 2'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Private Registry 2'
    repository: DotCast
    tags: $(Build.BuildId)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: $(Build.ArtifactStagingDirectory)