<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../DotCast.Infrastructure.AppUser.DotCast/DotCast.Infrastructure.AppUser.DotCast.csproj" />
    <ProjectReference Include="../DotCast.Infrastructure.Persistence.Marten/DotCast.Infrastructure.Persistence.Marten.csproj" />
    <ProjectReference Include="../DotCast.Infrastructure.Messaging.Base/DotCast.Infrastructure.Messaging.Base.csproj" />
    <ProjectReference Include="../DotCast.Infrastructure.CurrentUserProvider/DotCast.Infrastructure.CurrentUserProvider.csproj" />
  </ItemGroup>
</Project>
