name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, Raspberry]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish /p:DefineConstants=LINUX --configuration Release
    - uses: ncipollo/release-action@v1
      name: Create release
      with:
        artifacts: /home/pi/actions-runner/work/DotCast/DotCast/DotCast.Service/bin/Debug/netcoreapp3.1/publish/"
        token: ${{ secrets.GITHUB_TOKEN }}

