name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, Raspberry]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish /p:DefineConstants=LINUX --configuration Release
    
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r realease.zip "/home/pi/actions-runner/work/DotCast/DotCast/DotCast.Service/bin/Release/netcoreapp3.1/publish/"
      # Or, if you're on Windows: echo "Build number is ${env:BUILD_NUMBER}"
    - uses: ncipollo/release-action@v1
      name: Create release
      with:
        artifacts: realease.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: release
        commit: master

